### ISSUE TITLE
work around the "unknown data lines" problem we currently have.

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#14]
@JohannesAppel 

### I didn't get this "unknown data lines" yet.

Looking at your initial `def display()` https://github.com/JohannesAppel/johannesappel-/blob/0b6832fd40a0bc7757494809f35f34baa983fc09/LogData/src/main.py#L76
Your **shown data** depend on the received `frame.id`. You hold a list with `frame.id` and overwrite if the `frame.id` exists otherwise the Frame got appended to the list.

Therefore you never mind if you get 2 or 4 Frames of the same `Frame.id`. The old value are displayed again and again as long as a new Frame arrives and got overwritten. This use case does not need to know the number of Frames.

How large will this list grow?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
>How large will this list grow?

With the current bike I'm using to test the code on, it's `9` lines of data in total. But it displays at different times. In the first few milliseconds there's only 6/ and then as time passes the rest is also read. After about 2 seconds, everything is displayed. But this is different for other bikes. So that's why it can't be a fixed number.

>Therefore you never mind if you get 2 or 4 Frames of the same Frame.id

To explain why I'm doing this is the see what happens when you're putting your lights on on the bike, or turning the throttle. A specific byte, that's read from the `frame.data` will change, in the end I want to be able to isolate that byte and read the specific `frame.id` of that bike that's linked with it's lights for example.  
So the code needs to be able to work on any bike,and not just one specific one.
So as the data is read the list is either updated or appended, making sure all the data and the new data is always displayed. 

Hope this makes more sense.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Hope this makes more sense.

Yes.

We must change the display logic from 
- insert **one** Frame by Frame and count to `.cnt` 

to 

- display **all** received Frames. 
  Every `frame.id` have to be displayed **only** once with last received `frame.data`.

Please confirm:
- [x] Yes
- [ ] No
- [ ] Other

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I'm not sure if I understand you correctly. But it sounds right. I think it might solve the "flashing" problem.
